import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Product.module.css'
let json = require('../static/gallery.json');
import { useEffect, useState } from 'react';

const ProductOne: NextPage = () => {
    const [heading, setHeading] = useState('')
    const [imageUrl, setImageUrl] = useState('')
    useEffect(() => {
        const products = json.images
        products.forEach((element: any) => {
            console.log(element.url)
            console.log(window.location.search.split('?')[1])
            if (element.url === window.location.search.split('?')[1].split('=')[1]) {
                setHeading(element.heading)
                setImageUrl(element.imageUrl)
            }
        });
    }, [])
  return (
    <>
    <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className={styles.heading}>{heading}</h1>

        {!!imageUrl && <Image width={540} height={720} src={imageUrl} alt={heading} />}

    </div>
    </>
  )
}

export default ProductOne
